name: DebugBuild
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - checkpoint/directxgame-migration-stage16
      
env:
  SOLUTION_FILE_PATH: project/KuboEngine.sln
  CONFIGURATION: Debug

jobs:
  build:
    runs-on: windows-2025-vs2026

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2
        with:
          vs-version: '[18.0,19.0)'
          vs-prerelease: true
          msbuild-architecture: x64

      - name: Build
        run: msbuild $env:SOLUTION_FILE_PATH /p:Configuration=$env:CONFIGURATION /p:Platform=x64
